"use strict";
let num1 = 10;
console.log("number 1: ", num1);
let num2 = 7;
console.log("number 2: ", num2);
let sum = num1 + num2;
console.log("sum : ", sum);
let sub = num1 - num2;
console.log("subtraction : ", sub);
let mul = num1 * num2;
console.log("multiplication : ", mul);
let div = num1 / num2;
console.log("division : ", div);
let mod = num1 % num2;
console.log("modulo : ", mod);
let Calculation = (num1, num2) => {
    let sum = num1 + num2;
    console.log("sum : ", sum);
    let sub = num1 - num2;
    console.log("subtraction : ", sub);
    let mul = num1 * num2;
    console.log("multiplication : ", mul);
    let div = num1 / num2;
    console.log("division : ", div.toFixed(2));
    let mod = num1 % num2;
    console.log("modulo : ", mod);
};
console.log('-----------------------------------------');
Calculation(100, 32);
console.log('-----------------------------------------');
Calculation(52014, 532);
